---
version: '3'
services:
  # Strategy 1 - FirstStrategy (Conservative RSI + SMA) - MAIN UI
  freqtrade-first:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-first
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"  # Main FreqUI - shows all strategies
    command: >
      trade
      --logfile /freqtrade/user_data/logs/FirstStrategy/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/logs/FirstStrategy/trades.sqlite
      --config /freqtrade/user_data/strategies/FirstStrategy/config_dryrun.json
      --strategy FirstStrategy
      --strategy-path /freqtrade/user_data/strategies/FirstStrategy

  # Strategy 2 - SecondStrategy (EMA + MACD Trend Following)
  freqtrade-second:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-second
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8081:8081"  # API only - accessed via main UI
    command: >
      trade
      --logfile /freqtrade/user_data/logs/SecondStrategy/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/logs/SecondStrategy/trades.sqlite
      --config /freqtrade/user_data/strategies/SecondStrategy/config_dryrun.json
      --strategy SecondStrategy
      --strategy-path /freqtrade/user_data/strategies/SecondStrategy

  # Strategy 3 - ThirdStrategy (Bollinger Bands Scalping)
  freqtrade-third:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-third
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8082:8082"  # API only - accessed via main UI
    command: >
      trade
      --logfile /freqtrade/user_data/logs/ThirdStrategy/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/logs/ThirdStrategy/trades.sqlite
      --config /freqtrade/user_data/strategies/ThirdStrategy/config_dryrun.json
      --strategy ThirdStrategy
      --strategy-path /freqtrade/user_data/strategies/ThirdStrategy
