kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /Users/jacopom/Documents/Personal/Trading/Freqtrade/ftuser/user_data
    containerPath: /freqtrade/user_data
    readOnly: false
    selinuxRelabel: false
    propagation: None 