apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tradingstrategies.trading.io
spec:
  group: trading.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              strategy_class:
                type: string
              image:
                type: string
              port:
                type: integer
                minimum: 1
                maximum: 65535
              resources:
                type: object
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
          status:
            type: object
            properties:
              phase:
                type: string
              message:
                type: string
              last_updated:
                type: string
  scope: Namespaced
  names:
    plural: tradingstrategies
    singular: tradingstrategy
    kind: TradingStrategy
    shortNames:
    - ts 